package:
  name: kustomize
  version: 5.0.0
  epoch: 0
  description: "customization of kubernetes YAML configurations"
  target-architecture:
    - amd64
    - arm64
  copyright:
    - paths:
      - "*"
      license: Apache License 2.0
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${{package.version}}/kustomize_v${{package.version}}_linux_amd64.tar.gz
      expected-sha256: 2e8c28a80ce213528251f489db8d2dcbea7c63b986c8f7595a39fc76ff871cd7
  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${{package.version}}/kustomize_v${{package.version}}_linux_arm64.tar.gz
      expected-sha256: e97b12a83e7b9b0407cac97cac4c25bc135c42383bd3764d5544e32c96542eca
  - runs: |
      set +x 
      DEST_DIR="${{targets.destdir}}/usr/local/bin"
      mkdir -p "${DEST_DIR}"
      # only if kustomize package is available
      if [ -f kustomize ];
      then
        install -Dm755 kustomize $DEST_DIR/kustomize
      fi