# https://taskfile.dev

version: "3"

tasks:
  package:
    silent: true
    sources:
      - kustomize/melange.yaml
    generates:
      - packages/**/kustomize-5.0.0-r0.apk
    cmds:
      - docker run --privileged --rm -v "${PWD}":/work cgr.dev/chainguard/melange build  --signing-key /work/melange.rsa kustomize/melange.yaml
  