package:
  name: taskfile
  version: 3.20.0
  epoch: 0
  description: "a task runner / simpler Make alternative written in Go"
  target-architecture:
    - amd64
    - arm64
  copyright:
    - paths:
        - "*"
      license: MIT
  dependencies:
    runtime:

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
  packages:
    - git

pipeline:
  - uses: go/install
    with:
      package: github.com/go-task/task/v3/cmd/task
      version: v${{package.version}}
  - runs: |
      ${{targets.destdir}}/usr/bin/task --version | grep "Task version: v3.20.0"
  - uses: strip
