# https://taskfile.dev

version: "3"

env:
  NAME: gitops-devcontainer
  IMAGE_NAME: "kameshsampath/{{.NAME}}"
  IMAGE_TAG: v0.0.1-next


tasks:
  build_env:
    desc: start lima-vm to run melange and apko commands
    silent: true
    cmds:
      - limactl start --tty=false devtools-build-env.yaml
      - limactl shell devtools-build-env sudo su -c "HOME=\"${HOME}\" bash"

  delete_build_env:
    desc: stop and delete lima-vm devtools-build-env
    silent: true
    cmds:
      - limactl delete --force devtools-build-env

  build_melange_with_builtins:
    silent: true
    cmds:
      - docker buildx build -t docker.io/kameshsampath/melange --platform=linux/arm64 --platform=linux/amd64 --push -f Dockerfile .

  gen_key:
    desc: Generates keys to sign the local packages
    silent: true
    status:
      - test -f melange.rsa.pub
      - test -f melange.rsa
    cmds:
      - docker run --privileged --rm -v "${PWD}":/work cgr.dev/chainguard/melange keygen

  build_packages:
    desc: |
      Builds the tool packages that will be used in build tools container images
    silent: false
    deps:
      - gen_key
    cmds:
      - task: argocd
      - task: k3d
      - task: go-task
      - task: user_settings
      - task: vscode_devcontainer
      - task: yq

  build_containers:
    desc: |
      Builds tools container images
    silent: true
    deps:
      - build_packages
    cmds:
      - task: images:kube_devtools
      - task: images:gitops_devcontainer
  clean:
    desc: Cleans the packages and dist directory
    silent: true
    cmds:
      - rm -rf packages
      - rm -rf dist
      - mkdir -p dist packages
  test:
    desc: Runs tests
    silent: true
    dir: test
    cmds:
      - ./tests.bats

  #############################################################
  ## Tasks to build packages
  #############################################################
  argocd:
    cmds:
      - task: package
        vars:
          PACKAGE_FILE: argocd.yaml
          PACKAGE_NAME: argocd
          PACKAGE_VERSION: v2.5.10
  go-task:
    cmds:
      - task: package
        vars:
          PACKAGE_FILE: go-task.yaml
          PACKAGE_NAME: go-task
          PACKAGE_VERSION: v3.20.0
  k3d:
    cmds:
      - task: package
        vars:
          PACKAGE_FILE: k3d.yaml
          PACKAGE_NAME: k3d
          PACKAGE_VERSION: v5.4.7
  yq:
    cmds:
      - task: package
        vars:
          PACKAGE_FILE: yq.yaml
          PACKAGE_NAME: yq
          PACKAGE_VERSION: v4.38.0
  
  package:
    desc: builds the apk package
    silent: false
    internal: true
    generates:
      - packages/aarch64/{{.PACKAGE_NAME}}-{{.PACKAGE_VERSION}}-r0.apk
      - packages/x86_64/{{.PACKAGE_NAME}}-{{.PACKAGE_VERSION}}-r0.apk
    cmds:
      - docker run --privileged --rm -v "${PWD}":/work kameshsampath/melange build --arch=arm64 --signing-key /work/melange.rsa /work/{{.PACKAGE_FILE}}
