# https://taskfile.dev

version: "3"

env:
  NAME: gitops-devcontainer
  IMAGE_NAME: "kameshsampath/{{.NAME}}"
  IMAGE_TAG: v0.0.1-next

includes:
  argocd:
    taskfile: ./argocd/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  cosign:
    taskfile: ./cosign/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  crane:
    taskfile: ./crane/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  flux:
    taskfile: ./flux/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  helm:
    taskfile: ./helm/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  k3d:
    taskfile: ./k3d/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  ko:
    taskfile: ./ko/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  kubectl:
    taskfile: ./kubectl/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  kustomize:
    taskfile: ./kustomize/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  taskfile:
    taskfile: ./taskfile/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  user_settings:
    taskfile: ./dev-user-settings/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  dev_tools:
    taskfile: ./dev-tools/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  vscode_devcontainer:
    taskfile: ./vscode-devcontainer/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  images:
    taskfile: ./images/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  
tasks:
  apko_build_help:
    desc: Run apko build --help
    silent: true
    cmds:
      - docker run -it --rm cgr.dev/chainguard/apko build --help
  apko_publish_help:
    desc: Run apko publish --help
    silent: true
    cmds:
      - docker run -it --rm cgr.dev/chainguard/apko publish --help
  melange_build_help:
    desc: Run apko melange --help
    silent: true
    cmds:
      - docker run -it --rm cgr.dev/chainguard/melange build --help
  gen_key:
    desc: Generates keys to sign the local packages
    silent: true
    status:
      - test -f melange.rsa.pub
      - test -f melange.rsa
    cmds:
      - docker run --privileged --rm -v "${PWD}":/work cgr.dev/chainguard/melange keygen
  build_packages:
    desc: |
      Builds the tool packages that will be used in build tools container images
    silent: false
    deps:
      - gen_key
    cmds:
      - task: argocd:package
      - task: dev_tools:package
      - task: cosign:package
      - task: crane:package
      - task: flux:package
      - task: helm:package
      - task: k3d:package
      - task: ko:package
      - task: kubectl:package
      - task: kustomize:package
      - task: taskfile:package
      - task: user_settings:package
      - task: vscode_devcontainer:package
  build_containers:
    desc: |
      Builds tools container images
    silent: true
    deps:
      - build_packages
    cmds:
      - task: images:kube_devtools
      - task: images:gitops_devcontainer
  clean:
    desc: Cleans the packages and dist directory
    silent: true
    cmds:
      - rm -rf packages
      - rm -rf dist
      - mkdir -p dist packages
  test:
    desc: Runs tests
    silent: true
    dir: test
    cmds:
     - ./tests.bats
  