# https://taskfile.dev

version: "3"

env:
  NAME: gitops-devcontainer
  IMAGE_NAME: "kameshsampath/{{.NAME}}"
  IMAGE_TAG: v0.0.1-next

includes:
  argocd:
    taskfile: ./argocd/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  crane:
    taskfile: ./crane/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  flux:
    taskfile: ./flux/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  helm:
    taskfile: ./helm/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  k3d:
    taskfile: ./k3d/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  kubectl:
    taskfile: ./kubectl/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  kustomize:
    taskfile: ./kustomize/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  taskfile:
    taskfile: ./taskfile/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  user_settings:
    taskfile: ./dev-user-settings/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  dev_tools:
    taskfile: ./dev-tools/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  vscode_devcontainer:
    taskfile: ./vscode-devcontainer/Taskfile.yaml
    dir: "{{.ROOT_DIR}}"
  
tasks:
  apko_build_help:
    silent: true
    cmds:
      - docker run -it --rm cgr.dev/chainguard/apko build --help
  apko_publish_help:
    silent: true
    cmds:
      - docker run -it --rm cgr.dev/chainguard/apko publish --help
  melange_build_help:
    silent: true
    cmds:
      - docker run -it --rm cgr.dev/chainguard/melange build --help
  gen_key:
    silent: true
    status:
      - test -f melange.rsa.pub
      - test -f melange.rsa
    cmds:
      - docker run --privileged --rm -v "${PWD}":/work cgr.dev/chainguard/melange keygen
  build_packages:
    silent: false
    deps:
      - gen_key
    cmds:
      - task: argocd:package
      - task: dev_tools:package
      - task: crane:package
      - task: flux:package
      - task: helm:package
      - task: k3d:package
      - task: kubectl:package
      - task: kustomize:package
      - task: taskfile:package
      - task: user_settings:package
      - task: vscode_devcontainer:package
  build_container:
    silent: true
    deps:
      - build_packages
    sources:
      - "{{.TASKFILE_DIR}}/image.yaml"
    generates:
      - "{{.TASKFILE_DIR}}/dist/gitops-devcontainer_arm64.tar"
      - "{{.TASKFILE_DIR}}/dist/gitops-devcontainer_amd64.tar"
      - "{{.TASKFILE_DIR}}/dist/sbom-aarch64.spdx.json"
      - "{{.TASKFILE_DIR}}/dist/sbom-aarch64.cdx"
      - "{{.TASKFILE_DIR}}/dist/sbom-x86_64.cdx"
      - "{{.TASKFILE_DIR}}/dist/sbom-x86_64.spdx.json"
    cmds:
      - docker pull cgr.dev/chainguard/apko
      - mkdir -p "{{.TASKFILE_DIR}}/dist"
      - task: build_container_arm64
      - task: build_container_amd64
  build_container_arm64:
    silent: true
    internal: true
    cmds:
      - docker run -v "$PWD":/work cgr.dev/chainguard/apko build --build-arch=arm64 /work/image.yaml {{.IMAGE_NAME}}:{{.IMAGE_TAG}} /work/dist/{{.NAME}}_arm64.tar --debug
  build_container_amd64:
    silent: true
    internal: true
    cmds:
      - docker run -v "$PWD":/work cgr.dev/chainguard/apko build --build-arch=amd64 /work/image.yaml {{.IMAGE_NAME}}:{{.IMAGE_TAG}} /work/dist/{{.NAME}}_amd64.tar --debug
  clean:
    silent: true
    cmds:
      - rm -rf packages
      - rm -rf dist
      - mkdir -p dist packages
  test:
    silent: true
    dir: test
    cmds:
     - ./tests.bats
  