package:
  name: yq
  version: 4.30.8
  epoch: 0
  description: "yq is a portable command-line YAML, JSON, XML, CSV and properties processor"
  target-architecture:
    - amd64
    - arm64
  copyright:
    - paths:
        - "*"
      license: Apache License 2.0
  dependencies:
    runtime:

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os

pipeline:
  - uses: go/install
    with:
      package: github.com/mikefarah/yq/v4
      version: v${{package.version}}
  - runs: |
      ${{targets.destdir}}/usr/bin/yq --version | grep "version v${{package.version}}"
  - uses: strip
