package:
  name: dev-tools
  version: 0.0.1
  epoch: 0
  description: "tools that are useful with development"
  target-architecture:
    - arm64
    - amd64
  copyright:
    - paths:
      - "*"
      license: Apache License 2.0
  dependencies:
    runtime:
      - curl
      - jq
      - git
      - wget
      - yq
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - busybox
      - ca-certificates-bundle
pipeline:
  - runs: mkdir -p "${{targets.destdir}}"