# https://taskfile.dev

version: "3"

tasks:
  package:
    silent: true
    sources:
      - dev-tools/melange.yaml
    generates:
      - packages/aarch64/dev-tools-0.0.1-r0.apk
      - packages/x86_64/dev-tools-0.0.1-r0.apk
    cmds:
      - docker run --privileged --rm -v "${PWD}":/work cgr.dev/chainguard/melange build --arch=arm64,amd64 --signing-key /work/melange.rsa dev-tools/melange.yaml
  