# https://taskfile.dev

version: "3"

tasks:
  package:
    silent: true
    sources:
      - vscode-devcontainer/melange.yaml
    generates:
      - packages/aarch64/vscode-devcontainer-0.0.1-r0.apk
      - packages/x86_64/vscode-devcontainer-0.0.1-r0.apk
    cmds:
      - docker run --privileged --rm -v "${PWD}":/work cgr.dev/chainguard/melange build --arch=arm64,amd64 --signing-key /work/melange.rsa vscode-devcontainer/melange.yaml
  