# https://taskfile.dev

version: "3"

tasks:
  package:
    silent: true
    sources:
      - taskfile/melange.yaml
    generates:
      - packages/**/taskfile-3.20.0-r0.apk
    cmds:
      - docker run --privileged --rm -v "${PWD}":/work cgr.dev/chainguard/melange build  --signing-key /work/melange.rsa taskfile/melange.yaml
  