package:
  name: k3d
  version: 5.4.7
  epoch: 0
  description: "k3d cli utility"
  target-architecture:
    - amd64
    - arm64
  copyright:
    - paths:
        - "*"
      license: Apache License 2.0
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox
      - ca-certificates-bundle

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - uses: fetch
        if: ${{build.arch}} == 'x86_64'
        with:
          uri: https://github.com/k3d-io/k3d/releases/download/v${{package.version}}/k3d-linux-amd64
          extract: false
          expected-sha256: c54218d5bf6cb6e74987bf21f7820483f581b00c49fee11dbdb8c17c7829a025
      - uses: fetch
        if: ${{build.arch}} == 'aarch64'
        with:
          uri: https://github.com/k3d-io/k3d/releases/download/v${{package.version}}/k3d-linux-arm64
          extract: false
          expected-sha256: c8ceb55ed2ffe2015b915848d0b6eaa72dbc1358270dee4e0c12358c16231d40
  - runs: |
      set +x 
      DEST_DIR="${{targets.destdir}}/usr/local/bin"
      mkdir -p "${DEST_DIR}"
      # only if argocd-linux-* package is available
      if [ -f k3d-linux-amd64 ];
      then
        install -Dm755 k3d-linux-amd64 $DEST_DIR/k3d
      elif [ -f k3d-linux-arm64 ];
      then
       install -Dm755 k3d-linux-arm64 $DEST_DIR/k3d
      fi
