package:
  name: argocd
  version: 2.5.10
  epoch: 0
  description: "argo cd cli"
  target-architecture:
    - amd64
    - arm64
  copyright:
    - paths:
      - "*"
      license: Apache License 2.0
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://github.com/argoproj/argo-cd/releases/download/v${{package.version}}/argocd-linux-amd64
      extract: false
      expected-sha256: d3f24a281c8e1111ed6a4ab653b745f01e3965448b12c3b439033f29fd809884
  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://github.com/argoproj/argo-cd/releases/download/v${{package.version}}/argocd-linux-arm64
      extract: false
      expected-sha256: ba9b93d0d02d10af16b4201ae981015d6a41b4ffdb1ee2af6392c0b03859448f
  - runs: |
      set +x 
      mkdir -p "${{targets.destdir}}"
      DEST_DIR="${{targets.destdir}}/usr/local/bin"
      # only if argocd-linux-* package is available
      if [ -f argocd-linux-amd64 ];
      then
        install -Dm755 argocd-linux-amd64 $DEST_DIR/argocd
      elif [ -f argocd-linux-arm64 ];
      then
       install -Dm755 argocd-linux-arm64 $DEST_DIR/argocd
      fi
