# https://taskfile.dev

version: "3"

tasks:
  package:
    silent: true
    sources:
      - argocd/melange.yaml
    generates:
      - packages/**/argocd-2.5.10-r0.apk
    cmds:
      - docker run --privileged --rm -v "${PWD}":/work cgr.dev/chainguard/melange build  --signing-key /work/melange.rsa argocd/melange.yaml
  