package:
  name: ko
  version: 0.12.0
  epoch: 0
  description: "build and deploy go applications as containers"
  target-architecture:
    - amd64
    - arm64
  copyright:
    - paths:
        - "*"
      license: Apache License 2.0
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/ko-build/ko/archive/v${{package.version}}/ko-v${{package.version}}.tar.gz
      expected-sha256: cc42e9cde0b4d3380b680cf100c9be9acac67948f3dcfe65d71b87e2da797600
  - runs: |
      set +ex
      ls -ltr
      CGO_ENABLED=0 go build \
        -trimpath -ldflags "-s -w -X github.com/google/ko/pkg/commands.Version=v${{package.version}}" \
        -o "${{targets.destdir}}"/usr/local/bin/ko .
      echo "Built Version: ${{targets.destdir}}/usr/local/bin/ko version"