# https://taskfile.dev

version: "3"

tasks:
  package:
    silent: true
    sources:
      - kubectl/melange.yaml
    generates:
      - packages/**/kubectl-1.24.10-r0.apk
    cmds:
      - docker run --privileged --rm -v "${PWD}":/work cgr.dev/chainguard/melange build  --signing-key /work/melange.rsa kubectl/melange.yaml
  