# https://taskfile.dev

version: "3"

tasks:
  package:
    silent: true
    sources:
      - kubectl/melange.yaml
    generates:
      - packages/aarch64/kubectl-1.24.10-r0.apk
      - packages/x86_64/kubectl-1.24.10-r0.apk
    cmds:
      - docker run --privileged --rm -v "${PWD}":/work cgr.dev/chainguard/melange build  --arch=arm64,amd64 --signing-key /work/melange.rsa kubectl/melange.yaml
  