package:
  name: helm
  version: 3.11.0
  epoch: 0
  description: "helm package manager"
  target-architecture:
    - amd64
    - arm64
  copyright:
    - paths:
      - "*"
      license: Apache License 2.0
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://get.helm.sh/helm-v${{package.version}}-linux-amd64.tar.gz
      expected-sha256: 6c3440d829a56071a4386dd3ce6254eab113bc9b1fe924a6ee99f7ff869b9e0b
  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://get.helm.sh/helm-v${{package.version}}-linux-arm64.tar.gz
      expected-sha256: 57d36ff801ce8c0201ce9917c5a2d3b4da33e5d4ea154320962c7d6fb13e1f2c
  - runs: |
      set +x 
      DEST_DIR="${{targets.destdir}}/usr/local/bin"
      mkdir -p "${DEST_DIR}"
      # only if helm package is available
      if [ -f helm ];
      then
        install -Dm755 helm $DEST_DIR/helm
      fi
