package:
  name: dev-user-settings
  version: 0.0.1
  epoch: 0
  description: "tools and settings for dev user"
  target-architecture:
    - arm64
    - amd64
  copyright:
    - paths:
        - "*"
      license: Apache License 2.0
  dependencies:
    runtime:
      - bash
      - curl
      - ca-certificates-bundle
      - bash-completion
      - sudo
      - shadow
      - starship
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - busybox
      - ca-certificates-bundle
      - curl

pipeline:
  - uses: fetch
    with:
      uri: https://raw.githubusercontent.com/ahmetb/kubectl-aliases/master/.kubectl_aliases
      extract: false
      expected-sha256: 8c54b5bc800a51e013245b42ae79073177684799ee958474fa17d1b3175b7b3d
  - runs: |
      set +x 
      ls -ltra
      USER_HOME="${{targets.destdir}}"/home/dev
      SUDOERS_DIR="${{targets.destdir}}"/etc/sudoers.d
      mkdir -p $USER_HOME
      mkdir -p $SUDOERS_DIR
      mv suoders-dev $SUDOERS_DIR/dev
      chmod 0440  $SUDOERS_DIR/dev
      mv dev-user-bashrc $USER_HOME/.bashrc
      mv .kubectl_aliases $USER_HOME/.kubectl_aliases
