package:
  name: dev-user-settings
  version: 0.0.1
  epoch: 0
  description: "tools and settings for dev user"
  target-architecture:
    - arm64
    - amd64
  copyright:
    - paths:
      - "*"
      license: Apache License 2.0
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - busybox
      - ca-certificates-bundle
      - bash
      - curl
      - bash-completion
      - sudo
      - starship
     
pipeline:
  - if: ${{build.arch}} == 'x86_64' || ${{build.arch}} == 'aarch64'
    runs: |
      set +x 
      USER_HOME="${{targets.destdir}}/home/dev"
      SUDOERSD_DEV="${{targets.destdir}}/etc/sudoers.d"
      mkdir -p $USER_HOME
      mkdir -p $SUDOERSD_DEV
      echo 'dev ALL=\(root\) NOPASSWD:ALL' >  $SUDOERSD_DEV/dev
      chmod 0440  $SUDOERSD_DEV/dev
      curl -sL https://gist.githubusercontent.com/kameshsampath/49927b980080f9bec1bda78034eb54bd/raw/45b4725a4b96b0feacc3fac80344b7bf3231ae9d/dev-user-bashrc -o  $SUDOERSD_DEV/.bashrc
      curl -sL https://raw.githubusercontent.com/ahmetb/kubectl-aliases/master/.kubectl_aliases -o $USER_HOME/.kubectl_aliases