# https://taskfile.dev

version: "3"

tasks:
  package:
    silent: true
    sources:
      - dev-user-settings/melange.yaml
    generates:
      - packages/**/dev-user-settings-0.0.1-r0.apk
    cmds:
      - docker run --privileged --rm -v "${PWD}":/work cgr.dev/chainguard/melange build --arch $(uname -m) --signing-key /work/melange.rsa dev-user-settings/melange.yaml
  